# Site settings
title: Codude
header-img: img/home-bg.jpg
email: learn@codude.com
description: "Learn with fun at Codude"
baseurl: ""
url: "http://codude.com"
twitter_username: codude
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
